#!/usr/bin/env python

import os
import sys

from email import policy
from email.message import MIMEPart
from email.parser import BytesParser

import markdown

# TODO: 
# This script fails completely when the input email is UTF-8 encoded. 
# Can we change that? 
# I've tried generating a policy object: take a look at that later. 


# Cheat Sheet (Inspired by Akkana): 
# When given a 'multipart/alternative' message, the last part of the message is
# preferred as the authoritative message body (RFC 2046). If we attach the HTML
# last (as shown below), the HTML will be shown on most clients. 
# 
# An example email hierarchy is shown below. 
# multipart/mixed
#   multipart/alternative
#     text/plain
#     multipart/related
#       text/html
#       inline image
#   other attachment
#   other attachment


def add_html(msg):
    body = msg.get_body()

    if body.get_content_type() == 'text/plain': 
        body.make_alternative()
        text = body.get_payload()[0]
        text_mimepart = MIMEPart()
        text_mimepart.set_content(text.get_content())
        body.set_payload([text_mimepart, to_html_mimepart(text)])

    return msg


def to_html_mimepart(text):
    text_data = text.get_content()
    html_data = markdown.markdown(text_data)
    html_mimepart = MIMEPart()
    html_mimepart.set_content(html_data, subtype='html')
    return html_mimepart

if __name__ == "__main__":
    # Use CRLF newlines as per RFC.
    msg = BytesParser(policy=policy.SMTP).parse(sys.stdin.buffer)
    msg = add_html(msg)
    os.write(1, msg.as_bytes())
