#!/usr/bin/env python

import os
import sys

from email import policy
from email.mime.text import MIMEText
from email.parser import Parser

import markdown

# Cheat Sheet (Inspired by Akkana): 
# When given a 'multipart/alternative' message, the last part of the message is
# preferred as the authoritative message body (RFC 2046). If we attach the HTML
# last (as shown below), the HTML will be shown on most clients. 
# 
# An example email hierarchy is shown below. 
# multipart/mixed
#   multipart/alternative
#     text/plain
#     multipart/related
#       text/html
#       inline image
#   other attachment
#   other attachment


def add_html(msg):
    body = msg.get_body()

    if body.get_content_type() == 'text/plain': 
        body.make_alternative()
        mime_text = body.get_payload()[0]
        mime_html = MIMEText(to_html(mime_text.get_content()), 'html', 'utf-8')

        body.set_payload([text, html])

    return msg


def to_html(text):
    return markdown.markdown(text)

if __name__ == "__main__":
    # Read a MIME email from stdin, convert it, then print it to stdout.
    msg = Parser(policy=policy.default).parse(sys.stdin)
    msg = add_html(msg)
    os.write(1, msg.as_bytes())
