#!/bin/sh -e

while true; do
  acpi -b | grep -v 'unavailable' | awk '
  $3 ~ /Discharging/ { 
  if ((substr($4, 0, 2) + 0) < 10) 
    print "low"; 
  }' | ifne notify-send -u critical -a 'battery' 'low battery'
  sleep 5m
done

