#!/usr/bin/env python

import sys, time, random, signal

char_wait = 1/30
newline_wait = 1/5
if len(sys.argv) >= 2: 
    char_wait = 1 / int(sys.argv[1])
if len(sys.argv) >= 3:
    newline_wait = 1 / int(sys.argv[2])

def delaykey(delay=char_wait): 
    offset = (random.random() - 0.5) * delay / 5
    time.sleep(delay + offset)

signal.signal(signal.SIGINT, lambda x, y: sys.exit(1))

for line in sys.stdin: 
    for char in line: 
        if char == '\n': 
            delaykey(newline_wait)
        elif char == '\t': 
            delaykey(newline_wait)
        
        sys.stdout.write(char)
        sys.stdout.flush()
        delaykey(char_wait)
delaykey(newline_wait * 2)
