#!/bin/sh -e

# TODO: Ensure this script enherits the right environment when starting it from
# systemd. As of now, we're just running it with /bin/zsh from systemd.


# Count mail
count() {
  find "$HOME/.local/mail/INBOX" -type f | wc -l
}

# Make sure offlineimap isn't already running
if [ ! -z "$(pgrep offlineimap)" ]; then
  exit
fi

# Get old email count
old=$(count)
if ! nice offlineimap -o -u quiet; then
  exit 1
fi
# Get email count after sync
new=$(count)

if ! [ -e ~/disable-email-notifs-todo ]; then
  if [ "$new" -gt "$old" ]; then
    if [ "$((new - old))" -eq 1 ]; then
      msg='1 new email'
    else
      msg="$((new - old)) new emails"
    fi
    notify-send -a 'offlineimap' "$msg"
  fi
fi

# Now that we've downloaded our mail, index it.
notmuch new >/dev/null
