#!/bin/sh -e

# this isn't set if we're not starting from a shell
# edit: wait..maybe? I don't think we actually need the below line
export GNUPGHOME="$HOME/.local/share/gnupg"
# TODO: use pinentry to figure some shit out, this password crap is annoying


# Count mail
count() { 
  find "$HOME/.local/mail/INBOX" -type f | wc -l
}

# Make sure offlineimap isn't already running
if [ ! -z "$(pgrep offlineimap)" ]; then
  exit
fi

# Get old email count
old=$(count)
if ! offlineimap -o -u quiet; then
  notify-send -a 'offlineimap' 'could not sync email'
  exit 1
fi
# Get email count after sync
new=$(count)

if [ "$new" -gt "$old" ]; then
  if [ "$((new - old))" -eq 1 ]; then
    msg='1 new email'
  else
    msg="$((new - old)) new emails"
  fi
  notify-send -a 'offlineimap' "$msg"
fi
