#!/bin/sh

# We need this because reasons.
# sway doesn't export its control variables to dbus. and that's a problem
# for anything that needs dbus.

if hash dbus-update-activation-environment 2>/dev/null; then
  dbus-update-activation-environment --systemd \
    DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway
fi
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

# Stop running services, so they receive new env vars
# TODO: make these depend on sway session.target so we don't have to restart.
# Also -- how do we get different systemd unit instances for each session?
# looks like all sessions share a systemd --user?
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start wireplumber

systemctl --no-block --user start sway-session.target


