#!/bin/sh

# scale up ui for hdpi screens
export QT_SCALE_FACTOR=2 
export GDK_SCALE=2
export GDK_DPI_SCALE=-1 

userresources=$HOME/.config/xorg/xresources
usermodmap=$HOME/.config/xorg/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
