#!/bin/sh

# allow foreign access to the running xorg server
xhost +local:

export XCOMPOSEFILE=$HOME/.config/xorg/xcompose
export XCOMPOSECACHE=$HOME/.cache/xorg/compose-cache
export GTK_IM_MODULE=xim
export XMODIFIERS="@im=none"

userresources=$HOME/.config/xorg/xresources
usermodmap=$HOME/.config/xorg/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
