# espanso configuration file

toggle_key: "RIGHT_ALT"
auto_restart: false

matches:
  - trigger: "`-"
    replace: "—"

  - trigger: "`shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: "`date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "`time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M %p"

  # Shell commands
  - trigger: "`shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
